/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const TermsV3LazyImport = createFileRoute('/terms-v3')()
const TermsV2LazyImport = createFileRoute('/terms-v2')()
const TermsLazyImport = createFileRoute('/terms')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const TermsV3LazyRoute = TermsV3LazyImport.update({
  path: '/terms-v3',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/terms-v3.lazy').then((d) => d.Route))

const TermsV2LazyRoute = TermsV2LazyImport.update({
  path: '/terms-v2',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/terms-v2.lazy').then((d) => d.Route))

const TermsLazyRoute = TermsLazyImport.update({
  path: '/terms',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/terms.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsLazyImport
      parentRoute: typeof rootRoute
    }
    '/terms-v2': {
      id: '/terms-v2'
      path: '/terms-v2'
      fullPath: '/terms-v2'
      preLoaderRoute: typeof TermsV2LazyImport
      parentRoute: typeof rootRoute
    }
    '/terms-v3': {
      id: '/terms-v3'
      path: '/terms-v3'
      fullPath: '/terms-v3'
      preLoaderRoute: typeof TermsV3LazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  TermsLazyRoute,
  TermsV2LazyRoute,
  TermsV3LazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/terms",
        "/terms-v2",
        "/terms-v3"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/terms": {
      "filePath": "terms.lazy.tsx"
    },
    "/terms-v2": {
      "filePath": "terms-v2.lazy.tsx"
    },
    "/terms-v3": {
      "filePath": "terms-v3.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
